### ISSUE TITLE
piskvork调用出现问题

### ISSUE THREAD

**Issue by vigor95** [ChisBread/Chis#1]
编译工程后得到的可执行文件，用piskvork调用貌似不走子...不知道是不是我使用方法错误
但您在gomocup上的CHIS程序是可用的。

**Comment by ChisBread** [comment]
你好，感谢你的issue。
请问你是否在release模式下编译，并且开启了/MT编译选项呢？

**Comment by ChisBread** [comment]
还有一种可能就是，你忘了加pbrain-前缀。

**Comment by vigor95** [comment]
非常感谢，确实是我忘了加pbrain-前缀。

**Comment by ChisBread** [comment]
不客气。
