### ISSUE TITLE
您好，我在编译项目的时候遇到了一些问题

### ISSUE THREAD

**Issue by dark-flame-master** [ChisBread/Chis#2]
我这边是win7+vs2012，无奈您的项目是13的，于是我就手动改了一下项目文件；
不过之后vs还是跟我报错，说有语法错误：
`struct config {
		size_t SIZE = 15;//棋盘大小
		int RULE = 0;//规则类型（只支持freestyle
		//time ms
		time_t search_time = 29900;//一次搜索时间
		time_t timeout_match = 180000;//总搜索时间上限
		time_t time_left = 180000;//剩下的时间

		size_t hash_max_size = 1024*100;//100MB
		size_t search_depth = 8;
	};`
比如上面这段是在chis_type.h中的
我平常主要使用Java和C#，所以对C++不甚了解——但是在声明的同时直接赋值真的可以吗？
如果您确实就是这样也可以编译，那应该就是我的ide问题了；
如果确实这块有问题的话，希望您能告诉我改正方法

**Comment by ChisBread** [comment]
In class initialization feature(C++11)
VS2012 doesn't support it.

**Comment by ChisBread** [comment]
你好，
    我已经在issue中给出回复。Chis使用了部分C++11的特性，建议使用支持C++11的编译器编译Chis。
    感谢你对Chis的关注。:D


Bread

2017年3月25日 15:25，"Lijiawen" <notifications@github.com>写道：

**Comment by dark-flame-master** [comment]
thank you, i installed vs2015 and worked !
